# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-13 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('book_description', models.TextField(max_length=1000)),
                ('book_category', models.CharField(choices=[(b'Science fiction', b'Science fiction'), (b'Fiction', b'Fiction'), (b'Drama', b'Drama'), (b'Comedy', b'Comedy'), (b'Action and Adventure', b'Action and Adventure'), (b'Romance', b'Romance'), (b'Mystery', b'Mystery'), (b'Horror', b'Horror'), (b'Fantasy', b'Fantasy')], default=b'Science fiction', max_length=255)),
                ('book_image', models.ImageField(max_length=255, upload_to=b'books/static/images/book-images')),
                ('book_recomended', models.BooleanField(choices=[(True, b'Yes'), (False, b'No')], default=False)),
                ('book_rating', models.CharField(choices=[(b'0.5', b'1/2 stars'), (b'1', b'1 stars'), (b'1.5', b'1 1/2 stars'), (b'2', b'2 stars'), (b'2.5', b'2 1/2 stars'), (b'3', b'3 stars'), (b'3.5', b'3 1/2 stars'), (b'4', b'4 stars'), (b'4.5', b'4 1/2 stars'), (b'5', b'5 stars')], max_length=3)),
                ('book_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('book_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
