# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-16 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_pk', models.IntegerField(max_length=255)),
                ('cart_item_id', models.IntegerField(max_length=255)),
                ('item_title', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item_quantity', models.IntegerField()),
            ],
        ),
    ]
