# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-09 09:00
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('book_description', models.CharField(max_length=1000)),
                ('book_image', models.ImageField(max_length=255, upload_to=b'images/book_images')),
                ('book_rating', models.CharField(choices=[(b'0.5', b'1/2 stars'), (b'1', b'1 stars'), (b'1.5', b'1 1/2 stars'), (b'2', b'2 stars'), (b'2.5', b'2 1/2 stars'), (b'3', b'3 stars'), (b'3.5', b'3 1/2 stars'), (b'4', b'4 stars'), (b'4.5', b'4 1/2 stars'), (b'5', b'5 stars')], max_length=3)),
                ('book_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency=b'ZAR', max_digits=8)),
                ('book_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
