# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-09 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170609_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(max_length=1000),
        ),
    ]
