# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170623_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_username', models.CharField(max_length=55)),
                ('order_user_pk', models.IntegerField(max_length=255)),
                ('payment_id', models.CharField(max_length=255)),
                ('pf_payment_id', models.CharField(max_length=255)),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
