# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-09 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170609_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(max_length=255, upload_to=b'books/static/images/book-images'),
        ),
    ]
