# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_user_pk',
            field=models.IntegerField(),
        ),
    ]
