# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170711_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_user_pk',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
