# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-09 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170609_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_recomended',
            field=models.BooleanField(choices=[(True, b'Yes'), (False, b'No')], default=False),
        ),
    ]
