# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20170711_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_of_books',
            field=models.IntegerField(default=0),
        ),
    ]
