# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_order_quantity_of_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcartitems',
            name='item_checked_out',
            field=models.BooleanField(choices=[(True, b'Yes'), (False, b'No')], default=False),
        ),
    ]
