# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-09 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20170609_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.CharField(choices=[(b'Science fiction', b'Science fiction'), (b'Fiction', b'Fiction'), (b'Drama', b'Drama'), (b'Comedy', b'Comedy'), (b'Action and Adventure', b'Action and Adventure'), (b'Romance', b'Romance'), (b'Mystery', b'Mystery'), (b'Horror', b'Horror'), (b'Fantasy', b'Fantasy')], default=b'Science fiction', max_length=255),
        ),
    ]
