# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20170711_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcartitems',
            options={'verbose_name': 'Book Cart', 'verbose_name_plural': 'Book Carts'},
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='item_pk',
        ),
    ]
