# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20170712_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='order_payment_id',
            field=models.CharField(default=b'0', max_length=255),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='order_user_pk',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
