# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20170712_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(max_length=255, upload_to=b'images/author-images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(max_length=255, upload_to=b'images/book-images'),
        ),
    ]
